SELECT vt.ACCOUNTNUM,
       dpt.NAME,
       davsi.DISPLAYVALUE,
       davt.NAME
FROM dbo.VENDTABLE vt
    LEFT JOIN dbo.DIRPARTYTABLE dpt
        ON vt.PARTY = dpt.RECID
    LEFT JOIN dbo.DIMENSIONATTRIBUTEVALUESET davs
        ON davs.RECID = vt.DEFAULTDIMENSION
    LEFT JOIN dbo.DIMENSIONATTRIBUTEVALUESETITEM davsi
        ON davsi.DIMENSIONATTRIBUTEVALUESET = davs.RECID
    LEFT JOIN dbo.DIMENSIONATTRIBUTEVALUE dav
        ON dav.RECID = davsi.DIMENSIONATTRIBUTEVALUE
    LEFT JOIN dbo.DIMENSIONATTRIBUTE da
        ON da.RECID = dav.DIMENSIONATTRIBUTE
    LEFT JOIN dbo.DIMATTRIBUTEVENDTABLE davt
        ON davt.VALUE = davsi.DISPLAYVALUE
WHERE da.NAME = 'Vendor';